config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'pages#home'
	get 'about', to: 'pages#about'
	resources :articles
	get 'signup', to: 'users#new'
	resources :users, except: [:new]  
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	
	validates :title, presence: true, length: {minimum: 6, maximum: 100}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord

	before_save { self.email = email.downcase }
	has_many :articles, dependent: :destroy
	
	validates :username, presence:	true, 
						uniqueness: { case_sensitive: false }, 
						length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:	true, 
						uniqueness: { case_sensitive: false }, 
						length: { maximum: 105 },
						format: { with: VALID_EMAIL_REGEX }
	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "login please"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:show, :index]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	
	def index
		@articles = Article.paginate(page: params[:page], per_page: 3)
	end

	def show
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:notice] = 'Article was saved successfully'
			redirect_to @article
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @article.update(article_params)
			flash[:notice] = 'Article was updated successfully'
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	private 
	
	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title,:description)
	end

	def require_same_user
		if current_user != @article.user
			flash[:alert] = "you can only edit your own articles"
			redirect_to @article
		end
	end

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

	def about
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = "logged in"
			redirect_to user
		else
			flash.now[:alert] = "wrong details"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "loggeded out"
		redirect_to login_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:show, :index]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def new
		@user = User.new
	end
	
	def show
	end

	def index
		@users = User.paginate(page: params[:page], per_page: 2)
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "Welcome #{@user.username}!"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:notice] = 'User was updated successfully'
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil
		flash[:notice] = "user and articles deleted"
		redirect_to articles_path
	end

	private
	def user_params
		params.require(:user).permit(:username,:email,:password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user
			flash[:alert] = "you can only edit your own articles"
			redirect_to @article
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user)
		email = user.email.downcase
		hash = Digest::MD5.hexdigest(email)
		gurl = "https://www.gravatar.com/avatar/#{hash}"
		image_tag(gurl, alt: user.username)
	end
end

def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
	!!current_user
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<table>
	<thead>
		<tr>
		<th>User</th>
			<th>Title</th>
			<th>Description</th>
			<th colspan="3">Actions</th>
		</tr>
	</thead>

	<tbody>
		<% obj.each do |article| %>
			<tr>
				<td><%= article.user.username%></td>
				<td><%= article.title%></td>
				<td><%= article.description%></td>
				<td><%= link_to 'Show', article_path(article) %></td>
				<% if logged_in? && current_user == article.user %>
					<td><%= link_to 'Edit', edit_article_path(article) %></td>
					<td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?' } %></td>
				<% end %>	  

			</tr>
		<% end %>
	</tbody>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

	<% @article.errors.full_messages.each do |error| %>

		<%= error%>

	<% end %>

<% end %>

<%= form_with(model: @article, local: true) do |f| %>
	
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>

	<p>	<%= f.submit %></p>

<%end%>

app/views/articles/edit.html.erb
<h1>Edit Article: <%= @article.id  %></h1>

<%= render 'form' %>

<%= link_to 'Cancel', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
		<%= render 'articles', obj: @articles %>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
</br>
<%= link_to 'Create New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form'%>

<%= link_to 'Cancel', articles_path %>

app/views/articles/show.html.erb
<h1>Article: <%= @article.id %> </h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

</br>
<% if logged_in? && current_user == @article.user %>
	<%= link_to 'Edit', edit_article_path(@article) %>
	<%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Show All', articles_path %>

app/views/layouts/_messages.html.erb
		<% flash.each do |name, msg| %>
			<%= msg%>
		<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
       
				<% if logged_in? %>
					 <li class="nav-item">
            <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
        	</li>
				 <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
				<% else %>
 					<li class="nav-item">
          	<%= link_to 'Login', login_path, class: "nav-link" %>
        	</li>
								<li class="nav-item">
          	<%= link_to 'Signup', signup_path, class: "nav-link" %>
        	</li>
				<% end %>
      </ul>
    </div>
  </div>
</nav>		
	<%= render 'layouts/messages' %>
	<div class="container">
		<%= yield %>
	</div>  
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/home.html.erb
<h1>Home Page<h1>


<%= link_to 'Articles', articles_path %>
<%= link_to 'Signup', signup_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>

	<% @user.errors.full_messages.each do |error| %>

		<%= error%>

	<% end %>

<% end %>

<%= form_with(model: @user, local: true) do |f| %>
	
	<p>
		<%= f.label :username %>
		<%= f.text_field :username %>
	</p>

	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>

	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>

	<p>	<%= f.submit %></p>

<%end%>

app/views/users/edit.html.erb
<h1>Edit User: <%= @user.id  %></h1>

<%= render 'form' %>

<%= link_to 'Cancel', articles_path %>

app/views/users/index.html.erb
<h1>All Users</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<% @users.each do |user| %>

<div class="container">
	<div class="d-flex justify-content-center">
		<div class="card" style="width: 18rem;">
			<%= link_to gravatar_for(user)%>
			<div class="card-body">
				<h5 class="card-title">	<p><%=user.username%></p></h5>
				<p class="card-text">	
					<p><%= user.email %></p>
					<p><%= pluralize(user.articles.count, "articles") %></p>
				</p>
				<%= link_to 'View', user_path(user) %>
				<%= link_to 'Edit', edit_user_path(user) %>
			</div>
			  <div class="card-footer text-muted">
    			Joined <%= time_ago_in_words(user.created_at) %> ago
  		</div>
		</div>
	</div>
</div>
<% end %>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= render 'form'%>

<%= link_to 'Cancel', root_path %>

app/views/users/show.html.erb
<div class="container">
	<div class="d-flex justify-content-center">
		<div class="card" style="width: 18rem;">
			<%= link_to gravatar_for(@user)%>
			<div class="card-body">
				<h5 class="card-title">	<p><%=@user.username%></p></h5>
				<p class="card-text">	
					<p><%= @user.email %></p>
					<p><%= pluralize(@user.articles.count, "articles") %></p>
				</p>
				<%= link_to 'Edit', edit_user_path(@user) %>
				<%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: "Are you sure!?" } %>
			</div>
			  <div class="card-footer text-muted">
    			Joined <%= time_ago_in_words(@user.created_at) %> ago
  		</div>
		</div>
	</div>
</div>

<h2>Users Articles</h2>
<%= render 'articles/articles' , obj: @user.articles %>

</br>